config/routes.rb
S2s::Application.routes.draw do

  get "users/new"

  
  resources :rezepts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
   root :to                  => 'pages#home', :as => :home
   
  match "/stevia"            => "pages#stevia"
  match "/stevia_kaufen"     => "pages#stevia_kaufen"

  match "/signup",    to:   "users#new" 
  match "/signin",    to:   "sessions#new"
  match "/signout",   to:   "sessions#destroy", via: :delete
  
  match "/kontakt"           => "pages#kontakt" 
  match "/agb"               => "pages#agb"
  match "/impressum"         => "pages#impressum"
  match "/link"              => "pages#link"
  
  match "/was_ist_stevia"    => "pages#was_ist_stevia"
  match "/stevia_pulver"     => "pages#stevia_pulver"
  match "/stevia_pflanze"    => "pages#stevia_pflanze"
  match "/stevia_rezepte"    => "pages#stevia_rezepte"
  match "/stevia_gesundheit" => "pages#stevia_gesundheit"
  
  
    

end

app/models/rezept.rb
# == Schema Information
#
# Table name: rezepts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  zutaten     :text
#  zubereitung :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Rezept < ActiveRecord::Base
  attr_accessible :title, :zubereitung, :zutaten
  #validates_presence_of :title, :zubereitung, :zutaten
  #attr_accessible :content
  
  belongs_to :user
  
 # validates :content, presence:true, length: { maximum: 50 }
  
 
  
end

app/controllers/rezepts_controller.rb
class RezeptsController < ApplicationController
  # GET /rezepts
  # GET /rezepts.json
  def index
    @rezepts = Rezept.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rezepts }
    end
  end

  # GET /rezepts/1
  # GET /rezepts/1.json
  def show
    @rezept = Rezept.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rezept }
    end
  end

  # GET /rezepts/new
  # GET /rezepts/new.json
  def new
    @rezept = Rezept.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rezept }
    end
  end

  # GET /rezepts/1/edit
  def edit
    @rezept = Rezept.find(params[:id])
  end

  # POST /rezepts
  # POST /rezepts.json
  def create
    @rezept = Rezept.new(params[:rezept])

    respond_to do |format|
      if @rezept.save
        format.html { redirect_to @rezept, notice: 'Rezept was successfully created.' }
        format.json { render json: @rezept, status: :created, location: @rezept }
      else
        format.html { render action: "new" }
        format.json { render json: @rezept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rezepts/1
  # PUT /rezepts/1.json
  def update
    @rezept = Rezept.find(params[:id])

    respond_to do |format|
      if @rezept.update_attributes(params[:rezept])
        format.html { redirect_to @rezept, notice: 'Rezept was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rezept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rezepts/1
  # DELETE /rezepts/1.json
  def destroy
    @rezept = Rezept.find(params[:id])
    @rezept.destroy

    respond_to do |format|
      format.html { redirect_to rezepts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rezepts_helper.rb
module RezeptsHelper
end

app/views/rezepts/_form.html.erb
<%= simple_form_for @rezept, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :zutaten %>
  <%= f.input :zubereitung %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                rezepts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/rezepts/edit.html.erb
<%- model_class = @rezept.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rezepts/index.html.erb
<%- model_class = Rezept.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:zutaten) %></th>
      <th><%= model_class.human_attribute_name(:zubereitung) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @rezepts.each do |rezept| %>
      <tr style ="width:500px">
        <td><%= link_to rezept.id, rezept_path(rezept) %></td>
        <td><%= rezept.title %></td>
        <td><%= rezept.zutaten %></td>
        <td><%= rezept.zubereitung %></td>
        <td><%=l rezept.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rezept_path(rezept), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      rezept_path(rezept),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rezept_path,
            :class => 'btn btn-primary' %>

app/views/rezepts/new.html.erb
<h1> Neus Rezept</h1>
<%- model_class = @rezept.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rezepts/show.html.erb
<%- model_class = @rezept.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @rezept.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zutaten) %>:</strong></dt>
  <dd><%= @rezept.zutaten %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zubereitung) %>:</strong></dt>
  <dd><%= @rezept.zubereitung %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rezepts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rezept_path(@rezept), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              rezept_path(@rezept),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>