config/routes.rb
S2s::Application.routes.draw do

  get "users/new"

  
  resources :rezepts
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
   root :to                  => 'pages#home', :as => :home
   
  match "/stevia"            => "pages#stevia"
  match "/stevia_kaufen"     => "pages#stevia_kaufen"

  match "/signup",    to:   "users#new" 
  match "/signin",    to:   "sessions#new"
  match "/signout",   to:   "sessions#destroy", via: :delete
  
  match "/kontakt"           => "pages#kontakt" 
  match "/agb"               => "pages#agb"
  match "/impressum"         => "pages#impressum"
  match "/link"              => "pages#link"
  
  match "/was_ist_stevia"    => "pages#was_ist_stevia"
  match "/stevia_pulver"     => "pages#stevia_pulver"
  match "/stevia_pflanze"    => "pages#stevia_pflanze"
  match "/stevia_rezepte"    => "pages#stevia_rezepte"
  match "/stevia_gesundheit" => "pages#stevia_gesundheit"
  
  
    

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Home", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
        
          <li><%= link_to "Kontakt", kontakt_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", 'users_path' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", 'edit_user_path(current_user)', %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
     <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
      <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
      
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
 
      <%= csrf_meta_tags %>
     
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
    
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
        
          <div class="container"
          <% flash.each do |key, value| %>
              <div class="alert alert-<%= key %>"><%= value %></div>
                <% end %>
          <% flash.each do |key, value| %>
                <%= content_tag(:div, value, class: "alert alert-#{key}") %>

                <%= content_tag(:div, value, class: "alert alert-#{key}") %>
                
         <% end %>
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>           
            </a>
            <a class="brand" <%= link_to "stevia2sweet", home_path %></a>
            <div class="nav-collapse">
              <ul class="nav">           
                <li><%= link_to "Home", home_path %></li>
                 <ul class="nav">           
                  <li class="dropdown">     
                   <a href="#"
                     class="dropdown-toggle"
                     data-toggle="dropdown">  
                       Stevia 
                       <b class="caret"></b>  
                    </a>  
                    <ul class="dropdown-menu">
                      <li><%= link_to "Stevia",            stevia_path %></li>
                      <li><%= link_to "Was ist Steviaaa",    was_ist_stevia_path %></li>
                      <li><%= link_to "Stevia Pulver",     stevia_pulver_path %></li>
                      <li><%= link_to "Stevia Pflanze",    stevia_pflanze_path %></li>
                      <li><%= link_to "Stevia Rezepte",    stevia_rezepte_path %></li>             
                      <li><%= link_to "Stevia Gesundheit", stevia_gesundheit_path %></li>             
                    </ul>  
                   </li>  
                  </ul>
                    <li><%= link_to "Shop",    stevia_kaufen_path %></li>
                    <li><%= link_to "Rezepte", stevia_rezepte_path %></li>
                    <li><%= link_to "Kontakt", kontakt_path %></li>
                 </ul> 
                     
             <div class="social">
                 <%= link_to(image_tag("twitter.png", :size => "32x32"), "http://www.twitter.com/stevia2sweet1", :title => "twitter") %>
                 <%= link_to(image_tag("facebook.png", :size => "32x32"), "http://www.facebook.com/stevia2sweet", :title => "facebook") %>
                 <%= link_to(image_tag("gplus.png", :size => "32x32"), "https://plus.google.com/u/1/104476268963677560473/posts", :title => "gplus") %> 
             </div>          
   
         </div>
         </div>
       </div>
     </div>
   </div>

      <div class="container">
        <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
           <a class="close" data-dismiss="alert" href="#">×</a>
          <%= msg %>
        </div>
        <% end %>
        <div class="row">
          <div class="span12"><%= yield %></div>
            <div class="span3">
            <div class="adsense">
            <script type="text/javascript"><!--
            google_ad_client = "ca-pub-9657678993726539";
            /* s2s_home */
            google_ad_slot = "5291348480";
            google_ad_width = 728;
            google_ad_height = 90;
            //-->
            </script>
            <script type="text/javascript"
            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
            </script>   
          </div>         
         </div>
       </div>
     </div>
    </div>  
   <div id="footer">
      <div id="footer_container">
        <div class="footer_container_box">  
          <%= link_to "Impressum", impressum_path %>
          |
          <%= link_to "AGB", agb_path %>
          |
          <%= link_to "Link", link_path %> 
     </div>
  </div>
  
  <script type="text/javascript" src="http://use.typekit.com/dzs0fdt.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
         
  </body>
</html>